-- Generated by the database client.
CREATE TABLE brands(
    id SERIAL NOT NULL,
    name varchar(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE inventories(
    id SERIAL NOT NULL,
    product_id integer NOT NULL,
    quantity integer DEFAULT 0,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE logs(
    id SERIAL NOT NULL,
    "action" varchar(255) NOT NULL,
    catalog varchar(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    user_id integer,
    detail_last jsonb,
    detail_new jsonb
);

-- Generated by the database client.
CREATE TABLE payment_types(
    id SERIAL NOT NULL,
    name varchar(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE product_sales(
    id SERIAL NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    total_amount integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE products(
    id SERIAL NOT NULL,
    name varchar(255) NOT NULL,
    sku varchar(255) NOT NULL,
    price double precision DEFAULT 0,
    reorder_point integer DEFAULT 0,
    brand_id integer,
    supplier_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    description text,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE suppliers(
    id SERIAL NOT NULL,
    name varchar(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    address text,
    phone_number varchar(15),
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE users(
    id SERIAL NOT NULL,
    name varchar(255) NOT NULL,
    last_name varchar(255) NOT NULL,
    second_surname varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    deleted_at timestamp without time zone,
    phone_number varchar(15),
    PRIMARY KEY(id)
);