CREATE TABLE incomes (
    id SERIAL PRIMARY KEY,
    order_receive_id INTEGER,
    account_id INTEGER NOT NULL,
    amount DOUBLE PRECISION DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE
);